version: '3.8'
services:
  dev:
    image: sdpx/api
    container_name: api-dev
    ports:
      - 8081:5000
    links:
      - mysql-dev
    depends_on:
      - mysql-dev
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4dev$
      MYSQL_DATABASE: devDB
      MYSQL_HOST: mysql-dev

  test:
    image: sdpx/api
    container_name: api-test
    ports:
      - 8082:5000
    links:
      - mysql-test
    depends_on:
      - mysql-test
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4test$
      MYSQL_DATABASE: testDB
      MYSQL_HOST: mysql-test

  mysql-dev:
    image: sdpx/db
    container_name: db-dev
    ports:
      - 3308:3306
    volumes:
      - ./devDB/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data-dev:/var/lib/mysql 
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: dev1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4dev$
      MYSQL_DATABASE: devDB

  mysql-test:
    image: sdpx/db
    container_name: db-test
    ports:
      - 3309:3306
    volumes:
      - ./testDB/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data-test:/var/lib/mysql 
    environment:
      MYSQL_ROOT_USER: root 
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4test$
      MYSQL_DATABASE: testDB
      